### ISSUE TITLE
Template Error - Variable "type" does not exist

### ISSUE THREAD

**Issue by johndwells** [iainurquhart/craft_introvert#1]
Hi Iain,

Thanks for bringing introvert over to Craft! I just gave it a whirl and when I try to edit a custom field I get this Template Error thrown:

Variable "type" does not exist

Comes from line 05 in templates/settings.html, the `| t({ type: type|lower })` is the culprit. When I change this to simply `|  t` it's all working fine.

Cheers,
John

**Comment by iainurquhart** [comment]
That's weird, don't see that error at this end... I've made the update anyway :)

Still fumbling my way around this thing, cheers for the heads up.

**Comment by johndwells** [comment]
Thanks! Yeah same here, lots to learn.
