### ISSUE TITLE
Display issues in assets modal

### ISSUE THREAD

**Issue by keithmancuso** [iainurquhart/craft_introvert#2]
Loving the fieldtype so far.

Getting some display issues if we try and use it on an asset source?

Maybe the display is simplified to fit if its on assets.

https://www.dropbox.com/s/bkir3vlqxcl78yw/Screenshot%202014-05-20%2012.41.14.png

**Comment by iainurquhart** [comment]
Thanks for the heads up.

I've just pushed a fix to simplify the table layout if it's being called from an asset modal.

Iain
